name: Ship Routing CI Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: 1 - Download code
      uses: actions/checkout@v3

    - name: 2 - Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: 3 - Install libraries
      run: pip install -r requirements.txt

    - name: 4 - Run tests
      run: pytest tests/ -v